### ISSUE TITLE
'use of internal package … not allowed'

### ISSUE THREAD

**Issue by rudolfbyker** [OrkaConsultants/vodacom-balance-api#2]
I followed instructions to install go on Linux here https://golang.org/doc/install and then followed the instructions to run vodacom-balance-api here https://github.com/OrkaConsultants/vodacom-balance-api/blob/master/README.md and it results in the following error when executing `go run main.go`:

```
main.go:6:2: use of internal package vodacom-balance-api/vendor/github.com/OrkaConsultants/vodacom-balance-api/internal/core not allowed
```

I'm new to Go. What does this mean?

**Comment by lukekroon** [comment]
@rudolfbyker what is the full path of the `vodacom-balance-api` directory ?

**Comment by rudolfbyker** [comment]
`/home/dolf/go/src/vodacom-balance-api`

**Comment by lukekroon** [comment]
If you run `go env GOPATH` is it `/home/dolf/go` ?

The package must be in the correct path for go to work. I am also not that fluent in golang so that is the only thing I can think of now.

**Comment by rudolfbyker** [comment]
It is.

**Comment by lukekroon** [comment]
Try cloning it in `/home/dolf/go/src/github.com/OrkaConsultants/vodacom-balance-api` and then from inside `vodacom-balance-api` run the dep ensure to retrieve dependencies.

**Comment by rudolfbyker** [comment]
Nice, that works.
